name: ${project.name}
author: Lucariatias
version: ${project.version}
description: ${project.description}
main: io.github.vayleryn.vayleryncharacters.VaylerynCharacters
depend: [VaylerynLib]
commands:
    character:
        description: Character management commands
        aliases: [char]
        usage: /<command> [new|switch|card|set|extenddescription|list|revive]
    racekit:
        description: Claims your races kit, if any
        usage: /<command>
    stats:
        description: Shows your stats
        aliases: [statistics]
        usage: /<command>
    skillpoints:
        description: Shows your skill points
        aliases: [sp]
        usage: /<command>
permissions:
    vayleryn.characters.createmasheekwell:
        default: op
        description: Allows the creation of masheek wells
    vayleryn.characters.characters.unlimited:
        default: op
        description: Allows the creation of unlimited characters
    vayleryn.characters.command.character.revive
        default: op
        description: Allows characters to be revived