name: ${project.name}
author: Lucariatias
version: ${project.version}
description: ${project.description}
main: net.wayward_realms.waywardcharacters.WaywardCharacters
depend: [WaywardLib]
commands:
    character:
        description: Character management commands
        aliases: [char]
        usage: /<command> [new|switch|card|set|extenddescription|assignstatpoint|list|revive|hide|unhide|transfer|resetstatpoints]
    racekit:
        description: Claims your races kit, if any
        usage: /<command>
    stats:
        description: Shows your stats
        aliases: [statistics]
        usage: /<command>
    skillpoints:
        description: Shows your skill points
        aliases: [sp]
        usage: /<command>
    togglethirst:
        description: Toggles thirst
        usage: /<command>
    togglehunger:
        description: Toggles hunger
        usage: /<command>
    party:
        description: Parent command for party commands
        usage: /<command> [invite|join|leave|members|disband]
permissions:
    wayward.characters.createmasheekwell:
        default: op
        description: Allows the creation of masheek wells
    wayward.characters.characters.unlimited:
        default: op
        description: Allows the creation of unlimited characters
    wayward.characters.command.character.revive:
        default: op
        description: Allows characters to be revived
    wayward.characters.command.character.list.others:
        default: op
        description: Allows you to list other players characters
    wayward.characters.command.character.resetstatpoints:
        default: op
        description: Allows you to reset character stat points
    wayward.characters.command.togglehunger:
        default: op
        description: Allows you to toggle hunger