name: ${project.name}
author: Lucariatias
version: ${project.version}
description: ${project.description}
main: net.wayward_realms.waywardportals.WaywardPortals
depend: [WaywardLib]
commands:
    portal:
        description: Parent for all portal commands
        usage: /<command> [args...]
    untame:
        description: Untames an entity
        usage: /<command>
permissions:
    wayward.travel.command.portal.create:
        description: Allows the creation of portals
        default: op
    wayward.travel.boatsigns.create:
        description: Allows for the creation of boat signs
        default: op