name: ${project.name}
authors: [alyphen, Xslare, melodichand, Exodin, PsychoTea, sudhirmohanraj]
version: ${project.version}
description: ${project.description}
main: net.wayward_realms.waywardworldgen.WaywardWorldgen
load: STARTUP
depend: [WaywardLib]