name: ${project.name}
authors: [Lucariatias, Xslare, melodichand, Exodin, PsychoTea, sudhirmohanraj]
version: ${project.version}
main: net.wayward_realms.waywardprofessions.WaywardProfessions
description: ${project.description}
depend: [WaywardLib]
commands:
    efficiency:
        description: Shows efficiency for crafing, brewing and mining
        usage: /<command> [craft|mine|brew] (material)
    durability:
        description: Gets durability of item in hand
        usage: /<command>
    profession:
        description: Adds experience in profession skills
        usage: /<command> [craftefficiency|minefficiency|brewefficiency|maxdurability] (material) [amount]
    setprofession:
        description: Sets a profession to a predefined profession
        usage: /<command> [profession]
permissions:
    wayward.professions.command.profession:
        description: Allows addition of profession skill points
        default: op