name: ${project.name}
author: Lucariatias
version: ${project.version}
main: net.wayward_realms.waywardprofessions.WaywardProfessions
description: ${project.description}
commands:
    efficiency:
        description: Shows efficiency for crafing, brewing and mining
        usage: /<command> [craft|mine|brew] (material)
    durability:
        description: Gets durability of item in hand
        usage: /<command>