name: ${project.name}
author: Lucariatias
version: ${project.version}
description: ${project.description}
main: net.wayward_realms.waywardlocks.WaywardLocks
depend: [WaywardLib]
commands:
    keyring:
        description: Shows your keyring inventory
        usage: /<command>
    lock:
        description: Locks a door or chest, giving you the key
        usage: /<command>
    unlock:
        description: Unlocks a door or chest, provided you are holding the key
        usage: /<command>
    getkey:
        description: Gets a copy of the key to a chest or door
        usage: /<command>
permissions:
    wayward.locks.command.getkey:
        description: Allows you to get the key to any door or chest
        default: op