name: ${project.name}
author: Lucariatias
version: ${project.version}
description: ${project.description}
main: net.wayward_realms.waywardmechanics.WaywardMechanics
depend: [WaywardLib]
permissions:
    wayward.mechanics.secretswitch:
        description: Allows creation of secret switches
        default: op
    wayward.mechanics.portcullis.create:
        description: Allows creation of portcullises
        default: op
    wayward.mechanics.drawbridge.create:
        description: Allows creation of drawbridges
        default: op