name: ${project.name}
author: Lucariatias
version: ${project.version}
description: ${project.description}
main: net.wayward_realms.waywardmechanics.WaywardMechanics
depend: [WaywardLib]
permissions:
    wayward.mechanics.secretswitch:
        description: Allows creation of secret switches
        default: op