name: ${project.name}
authors: [Lucariatias, Xslare, melodichand, Exodin, PsychoTea, sudhirmohanraj]
version: ${project.version}
description: ${project.description}
main: net.wayward_realms.waywardeconomy.WaywardEconomy
depend: [WaywardLib]
commands:
    money:
        description: Money management commands
        usage: /<command> [help|pay|set]
    wallet:
        description: Opens your wallet
        usage: /<command>
    auction:
        description: Auction management commands
        usage: /<command> [create|set|openbidding|closebidding]
    bid:
        description: Bids on an auction
        usage: /<command> [player]
permissions:
    wayward.economy.command.money.set:
        description: Allows you to set someone's balance
        default: op
    wayward.economy.shop.free:
        description: Allows you to create shops for free
        default: false
    wayward.economy.shop.admin:
        description: Allows you to create admin shops
        default: op
    wayward.economy.bank.create:
        description: Allows you to create banks
        default: op
