experience-multiplier:
    CREEPER: 3
    SKELETON: 3
    SPIDER: 3
    GIANT: 100
    ZOMBIE: 2
    SLIME: 2
    GHAST: 10
    PIG_ZOMBIE: 5
    ENDERMAN: 5
    CAVE_SPIDER: 3
    SILVERFISH: 3
    BLAZE: 5
    MAGMA_CUBE: 2
    ENDER_DRAGON: 1000
    WITHER: 1000
    BAT: 1
    WITCH: 5
    PIG: 1
    SHEEP: 1
    COW: 1
    CHICKEN: 1
    SQUID: 1
    WOLF: 2
    MUSHROOM_COW: 1
    SNOWMAN: 1
    OCELOT: 1
    IRON_GOLEM: 1
    HORSE: 1
    VILLAGER: 1
    ENDER_CRYSTAL: 4
    PLAYER: 0