name: ${project.name}
author: Lucariatias
version: ${project.version}
description: ${project.description}
main: net.wayward_realms.waywardmonsters.WaywardMonsters
depend: [WaywardLib]
commands:
    entitylevel:
        description: Manages entity levels
        usage: /<command> [get|set]
permissions:
    wayward.monsters.trainingdummy:
        description: Allows you to create training dummies
        default: op
    wayward.monsters.command.entitylevel.set:
        description: Allows you to set entity levels
        default: op
    wayward.monsters.command.entitylevel.get:
        description: Allows you to get entity levels
        default: op