name: ${project.name}
authors: [alyphen, Xslare, melodichand, Exodin, PsychoTea, sudhirmohanraj]
version: ${project.version}
description: ${project.description}
main: net.wayward_realms.waywardmonsters.WaywardMonsters
depend: [WaywardLib]
commands:
    entitylevel:
        description: Manages entity levels
        usage: /<command> [get|set]
    bleed:
        description: Forces a player to bleed
        usage: /<command> [player]
permissions:
    wayward.monsters.command.bleed:
        description: Allows you to force players to bleed
        default: op
    wayward.monsters.trainingdummy:
        description: Allows you to create training dummies
        default: op
    wayward.monsters.command.entitylevel.set:
        description: Allows you to set entity levels
        default: op
    wayward.monsters.command.entitylevel.get:
        description: Allows you to get entity levels
        default: op
    wayward.monsters.target:
        description: Allows you to create targets
        default: op
