name: ${project.name}
author: Lucariatias
version: ${project.version}
description: ${project.description}
main: net.wayward_realms.waywardmoderation.WaywardModeration
depend: [WaywardLib]
commands:
    reputation:
        description: Manages reputation
        usage: /<command> [view|set|plus|minus]
        aliases: [rep]
    tempban:
        description: Temporarily bans a user
        usage: /<command> [player] [hours]
    ticket:
        description: Manages tickets
        usage: /<command> [create|close|teleport]
    vanish:
        description: Toggles vanishing
        usage: /<command>
    warn:
        description: Warns a player
        usage: /<command> [player] [reason]
    unwarn:
        description: Unwarns a player
        usage: /<command> [player] [reason]
    warnings:
        description: Views warnings
        usage: /<command> (player)
    amivanished:
        description: Checks whether you are vanished
        usage: /<command>
permissions:
    wayward.moderation.command.reputation.set:
        description: Allows you to set reputation
        default: op
    wayward.moderation.command.reputation.plus:
        description: Allows you to add reputation
        default: op
    wayward.moderation.command.reputation.minus:
        description: Allows you to take reputation
        default: op
    wayward.moderation.command.tempban:
        description: Allows you to temporarily ban users
        default: op
    wayward.moderation.command.ticket.close:
        description: Allows you to close tickets that are not your own
        default: op
    wayward.moderation.command.ticket.teleport:
        description: Allows you to teleport to ticket locations
        default: op
    wayward.moderation.command.ticket.list:
        description: Allows you to list tickets
        default: op
    wayward.moderation.command.vanish:
        description: Allows you to toggle vanish
        default: op
    wayward.moderation.command.warnings:
        description: Allows you to view another players warnings
        default: op
    wayward.moderation.command.warn:
        description: Allows you to warn people
        default: op
    wayward.moderation.vanish.see.tier1:
        description: Allows you to see all vanished people
        default: op
    wayward.moderation.vanish.see.tier2:
        description: Allows you to see vanished people tier 2 and below
        default: false
    wayward.moderation.vanish.see.tier3:
        description: Allows you to see vanished people tier 3 and below
        default: false