name: ${project.name}
authors: [Lucariatias, Xslare, melodichand, Exodin, PsychoTea, sudhirmohanraj]
version: ${project.version}
description: ${project.description}
main: net.wayward_realms.waywardskills.WaywardSkills
depend: [WaywardLib]
commands:
    spell:
        description: Uses a spell
        usage: /<command> [spell]
    bindspell:
        description: Binds a spell to your item in hand
        usage: /<command>
    spellinfo:
        description: Shows the description for a spell
        usage: /<command> [spell]
    skill:
        description: Uses a skill
        usage: /<command> [skill]
    bindskill:
        description: Binds a skill to your item in hand
        usage: /<command>
    skillinfo:
        description: Shows the description for a skill
        usage: /<command> [skill]
    getscroll:
        description: Creates a scroll for a spell
        usage: /<command> [spell]
    specialisation:
        description: Opens the specialisation inventory
        usage: /<command>
        aliases: [specialise, spec]
    level:
        description: Level management commands
        usage: /<command> [info|setlevel|addexp]
permissions:
    wayward.skills.command.getscroll:
        description: Allows you to get a scroll for a spell
        default: op
    wayward.skills.command.level.info:
        description: Allows you to see other peoples levels
        default: op
    wayward.skills.command.level.setlevel:
        description: Allows you to set levels
        default: op
    wayward.skills.command.level.addexp:
        description: Allows you to add experience
        default: op
