name: ${project.name}
author: Lucariatias
version: ${project.version}
description: ${project.description}
main: net.wayward_realms.waywardclasses.WaywardClasses
depend: [WaywardLib]
commands:
    class:
        description: Parent command for all class commands
        usage: /<command> [set|info|list|setlevel|addexp]
permissions:
    wayward.classes.command.addexp:
        description: Old node that allows you to add exp
        default: op
    wayward.classes.command.getclass:
        description: Old node that allows you to get other peoples classes
        default: op
    wayward.classes.command.getlevel:
        description: Old node that allows you to get other peoples levels
        default: op
    wayward.classes.command.setclass:
        description: Old node that allows you to set other peoples classes
        default: op
    wayward.classes.command.setlevel:
        description: Old node that allows you to set levels
        default: op
    wayward.classes.command.viewzeropoints:
        description: Allows you to view zero points
        default: op
    wayward.classes.command.class.set:
        description: Allows you to set other peoples classes
        default: op
    wayward.classes.command.class.info:
        description: Allows you to view info on other peoples classes
        default: op
    wayward.classes.command.class.setlevel:
        description: Allows you to set levels
        default: op
    wayward.classes.command.class.addexp:
        description: Allows you to add exp
        default: op