name: ${project.name}
authors: [alyphen, Xslare, melodichand, Exodin, PsychoTea, sudhirmohanraj]
version: ${project.version}
description: ${project.description}
main: net.wayward_realms.waywardevents.WaywardEvents
depend: [WaywardLib]
commands:
    dungeon:
        description: Used for creating and modifying dungeons
        usage: /<command> [create|modify]
    radiusemote:
        description: Broadcasts a world emote with the given radius and message
        usage: /<command> [radius] [message]
    createeffect:
        description: Creates a visual or sound effect for a player or at a location
        usage: /<command> [location|player] [effect]
    eventcharacter:
        description: Manages event characters
        usage: /<command>
        aliases: [ec, echar, eventchar, echaracter]
    blockdescription:
        description: Modifies block descriptions
        usage: /<command>
        aliases: [blockdesc, blockdescriptor, bdesc]
permissions:
    wayward.events.command.radiusemote:
        description: Allows you to broadcast world emotes with a radius
        default: op
    wayward.events.command.dungeon.create:
        description: Allows you to create dungeons
        default: op
    wayward.events.command.dungeon.modify:
        description: Allows you to modify dungeons
        default: op
    wayward.events.command.dungeon.modify.other:
        description: Allows you to modify other peoples dungeons
        default: op
    wayward.events.command.createeffect:
        description: Allows you to create effects
        default: op
    wayward.events.command.eventcharacter:
        description: Allows you to use event characters
        default: op
    wayward.events.command.blockdescription:
        description: Allows you to modify block descriptions
        default: op
