name: ${project.name}
authors: [Lucariatias, Xslare, melodichand, Exodin, PsychoTea, sudhirmohanraj]
version: ${project.version}
description: ${project.description}
main: net.wayward_realms.waywardlib.Wayward
depend: [ProtocolLib]
commands:
    refreshprofile:
        description: Invalidates your profile so it has to be re-requested next time it is needed
        usage: /<command>