channels:
  general:
    colour: GRAY
    radius: -1
    format: '&7[%channel%] %ign%&7: &f%message%'
    garble-enabled: false
    irc:
      enabled: true
      channel: '#wayward-general'
      whitelist: false
    broadcasts:
      enabled: false
    ops: []
    hops: []
    voice: []
  say:
    colour: GREEN
    radius: 16
    format: '&a%player% says&a: &f%message%'
    garble-enabled: true
    irc:
      enabled: false
      channel: 'null'
      whitelist: false
    broadcasts:
      enabled: false
    ops: []
    hops: []
    voice: []
  shout:
    colour: DARK_RED
    radius: 64
    format: '&4%player% shouts&4: &f%message%'
    garble-enabled: true
    irc:
      enabled: false
      channel: 'null'
      whitelist: false
    broadcasts:
      enabled: false
    ops: []
    hops: []
    voice: []
  whisper:
    colour: AQUA
    radius: 4
    format: '&b%player% whispers&b: &f%message%'
    garble-enabled: true
    irc:
      enabled: false
      channel: 'null'
      whitelist: false
    broadcasts:
      enabled: false
    ops: []
    hops: []
    voice: []
  staff:
    colour: DARK_PURPLE
    radius: -1
    format: '&5[%channel%] %ign%&5: &f%message%'
    garble-enabled: false
    irc:
      enabled: true
      channel: '#wayward-staff'
      whitelist: true
    broadcasts:
      enabled: false
    ops: []
    hops: []
    voice: []
  dev:
    colour: YELLOW
    radius: -1
    format: '&e[%channel%] %ign%&e: &f%message%'
    garble-enabled: false
    irc:
      enabled: true
      channel: '#wayward-dev'
      whitelist: false
    broadcasts:
      enabled: false
    ops: []
    hops: []
    voice: []
  support:
    colour: DARK_GREEN
    radius: -1
    format: '&2[%channel%] %ign%&2: &f%message%'
    garble-enabled: false
    irc:
      enabled: true
      channel: '#wayward-support'
      whitelist: false
    broadcasts:
      enabled: false
    ops: []
    hops: []
    voice: []
  ooc:
    colour: BLUE
    radius: 16
    format: '&9[%channel%] %ign%&9: &f%message%'
    garble-enabled: false
    irc:
      enabled: false
      channel: 'null'
      whitelist: false
    broadcasts:
      enabled: false
    ops: []
    hops: []
    voice: []
  info:
    colour: WHITE
    radius: -1
    format: '&f[&a%channel%&f] %message%'
    garble-enabled: false
    irc:
      enabled: false
      channel: 'null'
      whitelist: false
    broadcasts:
      enabled: true
      possible:
      - 'Remember to vote on PMC!'
      - 'Check out the forums daily for updates on news and general discussion.'
      - 'Drop into IRC at #wayward-general to talk in general chat even while offline!'
    ops: []
    hops: []
    voice: []
emotes:
  radius: 16
  format: '&e&o%player% &e&o%message%'
default-channel: general
irc:
  enabled: true
broadcasts:
  delay: 120
