time-slow-factor: 4
daily-messages:
- '"That makes sense!"'
- '"You can always grind on a sheep!"'
- '"I am the best butt-kisser around!"'
- '"Dwarves are short!"'
- '"You probably think you''re ugly, but you''re actually pretty decent!"'
- '"Oh no... I must hide my stupidity!"'
- '"Dammit!"'
- '"Why stops me from quoting myself? Huh!?"'
- '"Oh shit, my thirst is 4!"'
- 'Train hard!'
- '"Be excellent to each other. And... PARTY ON DUDES!"'
- '"Evil will always triumph over good because good is dumb."'
- '"There''s only two things I hate in this world. People who are intolerant of other people''s cultures and the Dwarves."'
- '"I''m sure that we can handle this situation maturely, just like the responsible adults that we are. Isn''t that right, Mr. Poopy Pants?"'
- '"The only thing we don''t have a god for is premature ejaculation but I hear that''s coming quickly."'
- '"I fart in your general direction. Your mother was a hamster and your father smelt of elderberries.  Now go away, or I shall taunt you a second time."'
- '"Time marches on and sooner or later you realize it is marching across your face."'
- '"Fat, drunk, and stupid is no way to go through life, son."'
- '"Listen, strange women lyin'' in ponds distributin'' swords is no basis for a system of government. Supreme executive power derives from a mandate from the masses, not from some farcical aquatic ceremony."'
- '"If she weighed the same as a duck... she''s made of wood. And therefore... a witch!'
- '"Look, you stupid Bastard. You''ve got no arms left."'
- '"Oh, but you can''t expect to wield supreme executive power just because some watery tart threw a sword at you."'
- '"We are now the Knights who say... "Ekki-Ekki-Ekki-Ekki-PTANG. Zoom-Boing. Z''nourrwringmm."'
- '"...and that, my liege, is how we know the Earth to be banana shaped."'
- '"This new learning amazes me, Sir Bedevere. Explain again how sheep''s bladders may be employed to prevent earthquakes."'
- '"That''s the most foul, cruel, and bad-tempered rodent you ever set eyes on!"'
- '"Oh, king eh? Very nice. And how''d you get that, eh? By exploiting the workers. By hanging on to outdated imperialist dogma which perpetuates the economic and social differences in our society."'
- '"I *warned* you, but did you listen to me? Oh, no, you *knew*, didn''t you? Oh, it''s just a harmless little *bunny*, isn''t it?"'
- '"Don''t like her? What''s wrong with her? She''s beautiful, she''s rich, she''s got huge... tracts of land."'
- '"You must spank her well, and after you are done with her, you may deal with her as you like... and then... spank me."'
distance-command:
    item-requirement:
        ==: org.bukkit.inventory.ItemStack
        type: COMPASS
    maximum-distance: -1
track-command:
    item-requirement:
        ==: org.bukkit.inventory.ItemStack
        type: COMPASS
    maximum-distance: -1